Adds logo link and functionality
gregrickaby/reddit-image-viewer pull request #398
Opened 2022-10-06 03:49 UTC by AloyBranCheung

Closes #394

### Description

What does your feature do? Give some context...
This features allows the standard UX behavior of clicking the brand logo to head back to start/homepage. In the case of this app, it clears the search bar and returns  `itookapicture` as the default start images

Implementation: 
I moved the input state to the parent component so that the `<Header />` component could also access the state. That way, when the brand icon is clicked, the search bar can be set to a blank. 

To show `itookapicture` images when clicked, I used a template literal to check if the state is empty to default to `itookapicture`

### Screenshot

If possible, add some screenshots of your feature.

### Verification

How will a stakeholder test this?

1.Load the homepage
1.Search for subreddit pictures, try AnimalCrossing (i love that game)
1.Click the brand logo, should navigate you back to `itookapicture` subreddit

2022-10-06 12:45 UTC, gregrickaby requested changes
@AloyBranCheung Thank you for doing this. I have two things...

Rather than lifting state up to the `<Header />`, can you move the state management to the `<RedditProvider />` instead? I'd rather not have several locations handling state if possible. 

Also, when you click the logo, the feed doesn't reset to `itookapicture`...it just clears the `<Search />` component.

2022-10-06 13:37 UTC, gregrickaby commented
@AloyBranCheung I anticipated this, so I just pushed up ENV var instructions 😄 

https://github.com/gregrickaby/reddit-image-viewer/blob/main/CONTRIBUTING.md#env-variables

2022-10-06 13:46 UTC, AloyBranCheung commented
I see it now thanks for instructions. Sorry for trying to get away with just network traffic 😂😂😭😭😭

2022-10-06 22:48 UTC, gregrickaby commented
@AloyBranCheung FYI: #400 changed which ENV vars are required. Please view the updated [CONTRIBUTING](https://github.com/gregrickaby/reddit-image-viewer/blob/main/CONTRIBUTING.md#env-variables) doc.

Sorry in advanced for all the ENV switcharoos, but the `Bearer` token kept expiring, which broke the search ☹️ It should be stable now!

2022-10-07 00:30 UTC, AloyBranCheung commented
Gotchu thanks for letting me know. I just synced the repo and updated my branch. Hopefully I have time tonight to start cracking at it.

2022-10-07 01:15 UTC, AloyBranCheung commented
@gregrickaby I think this should work

2022-10-07 12:27 UTC, gregrickaby requested changes

2022-10-07 12:27 UTC, gregrickaby commented on components/RedditProvider.tsx
> +  setSearchInput: React.Dispatch<React.SetStateAction<string>>
@AloyBranCheung While I appreciate the verboseness of this type, I'd rather it stay in line with the rest of the project. Can you update it to something like: `(searchInput: string) => void` 

Thank you

2022-10-07 12:27 UTC, gregrickaby commented on components/Search.tsx
> +  const handleChange = (string: string) => {
@AloyBranCheung Can you please make this named function?

```ts
function handleChange(string: string) {
  setSearchInput(string)
}

2022-10-07 13:55 UTC, gregrickaby approved these changes
@AloyBranCheung 👏🏻👏🏻 Way to stick with it. Thank you so much for your contribution! 🥳🙏🏻

2022-10-07 13:55 UTC, merged

2022-10-07 13:58 UTC, AloyBranCheung commented
@gregrickaby thanks for your patience and guidance :)